server:
  port: ${PORT}

spring:
  application:
    name: ${SPRING_APPLICATION_NAME}

  r2dbc:
    url: ${SPRING_R2DBC_URL}
    username: ${SPRING_R2DBC_USERNAME}
    password: ${SPRING_R2DBC_PASSWORD}

  sql:
    init:
      mode: ${SPRING_SQL_INIT_MODE}

email:
  from: ${MAIL_FROM}
  resend:
    api-key: ${RESEND_API_KEY}

management:
  health:
    r2dbc:
      enabled: ${MANAGEMENT_HEALTH_R2DBC_ENABLED}
    mail:
      enabled: ${MANAGEMENT_HEALTH_MAIL_ENABLED}

logging:
  level:
    org.springframework.r2dbc: ${LOGGING_LEVEL_R2DBC}
    com.vendingcom.auth_service: ${LOGGING_LEVEL_APP}

jwt:
  secret: ${JWT_SECRET}
  expiration-minutes: ${JWT_EXPIRATION_MINUTES}

auth:
  password-recovery:
    code-expiration-minutes: ${PASSWORD_RECOVERY_EXPIRATION_MINUTES}
    max-attempts: ${PASSWORD_RECOVERY_MAX_ATTEMPTS}
    request-cooldown-minutes: ${PASSWORD_RECOVERY_COOLDOWN_MINUTES}

springdoc:
  api-docs:
    path: ${SPRINGDOC_API_DOCS_PATH}
  swagger-ui:
    path: ${SPRINGDOC_SWAGGER_UI_PATH}
    operations-sorter: ${SPRINGDOC_SWAGGER_UI_OPERATIONS_SORTER}
    tags-sorter: ${SPRINGDOC_SWAGGER_UI_TAGS_SORTER}