server:
  port: ${PORT:8081}

spring:
  application:
    name: vendingcom-auth-service

  r2dbc:
    url: ${SPRING_R2DBC_URL:r2dbc:postgresql://localhost:5432/postgres}
    username: ${SPRING_R2DBC_USERNAME:postgres}
    password: ${SPRING_R2DBC_PASSWORD:123software}

  sql:
    init:
      mode: never

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:adolfo.berrocal@vallegrande.edu.pe}
    password: ${MAIL_PASSWORD:gvpa jfui hrjj yqlh}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

management:
  health:
    r2dbc:
      enabled: true
    mail:
      enabled: false

logging:
  level:
    org.springframework.r2dbc: DEBUG
    com.vendingcom.auth_service: DEBUG

jwt:
  secret: ${JWT_SECRET:VENDINGCOM_AUTH_SERVICE_SECRET_KEY_2026_DEVELOPMENT_ONLY_CHANGE_ME_123456789}
  expiration-minutes: ${JWT_EXPIRATION_MINUTES:60}

auth:
  password-recovery:
    code-expiration-minutes: ${PASSWORD_RECOVERY_EXPIRATION_MINUTES:10}
    max-attempts: ${PASSWORD_RECOVERY_MAX_ATTEMPTS:3}
    request-cooldown-minutes: ${PASSWORD_RECOVERY_COOLDOWN_MINUTES:2}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha